<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first();
        $seller1 = User::where('email', 'seller@example.com')->first();
        $seller2 = User::where('email', 'glow@example.com')->first();

        $catSkincare = Category::where('name', 'Skincare')->first();
        $catMakeup = Category::where('name', 'Makeup & Cosmetics')->first();
        $catHaircare = Category::where('name', 'Haircare & Styling')->first();
        $catFragrance = Category::where('name', 'Fragrances & Perfumes')->first();
        $catBodycare = Category::where('name', 'Bath & Body Care')->first();
        $catTools = Category::where('name', 'Beauty Tools & Accessories')->first();
        $catOrganic = Category::where('name', 'Organic & Herbal')->first();

        $products = [
            // --- SKINCARE ---
            [
                'user_id' => $seller1?->id,
                'category_id' => $catSkincare?->id,
                'category' => 'Skincare',
                'name' => 'The Ordinary Niacinamide 10% + Zinc 1%',
                'brand' => 'The Ordinary',
                'sku' => 'SKU-ORD-NIA-30',
                'price' => 2850.00,
                'original_price' => 3400.00,
                'badge' => 'Bestseller',
                'stock_quantity' => 120,
                'rating' => 4.9,
                'reviews_count' => 342,
                'is_featured' => true,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'High-strength vitamin and mineral blemish formula that reduces the appearance of skin blemishes and congestion.',
                'description' => 'Niacinamide (Vitamin B3) is indicated to reduce the appearance of skin blemishes and signs of congestion. A high 10% concentration of this vitamin is supported in the formula by zinc salt of pyrrolidone carboxylic acid to balance visible aspects of sebum activity.',
                'short_features' => [
                    'Reduces blemish appearance and pore congestion',
                    'Balances natural sebum and oil production',
                    'Smooths texture and brightens skin tone',
                    'Cruelty-Free, Vegan, Fragrance-Free',
                ],
                'usage_instructions' => 'Apply to entire face morning and evening before heavier creams. If irritation occurs, cease use and consult a physician.',
                'ingredients' => 'Aqua (Water), Niacinamide, Pentylene Glycol, Zinc PCA, Dimethyl Isosorbide, Tamarindus Indica Seed Gum, Xanthan gum, Isoceteth-20, Ethoxydiglycol, Phenoxyethanol, Chlorphenesin.',
            ],
            [
                'user_id' => $seller2?->id,
                'category_id' => $catSkincare?->id,
                'category' => 'Skincare',
                'name' => 'CeraVe Hydrating Facial Cleanser 237ml',
                'brand' => 'CeraVe',
                'sku' => 'SKU-CER-HYD-237',
                'price' => 4200.00,
                'original_price' => 4800.00,
                'badge' => 'Dermatologist Pick',
                'stock_quantity' => 85,
                'rating' => 4.8,
                'reviews_count' => 218,
                'is_featured' => true,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'Gentle lotion cleanser with hyaluronic acid & 3 essential ceramides for normal to dry skin.',
                'description' => 'Developed with dermatologists, CeraVe Hydrating Facial Cleanser cleanses, hydrates, and helps restore the protective skin barrier with three essential ceramides (1, 3, 6-II). The formula also contains hyaluronic acid to help retain skin’s natural moisture.',
                'short_features' => [
                    'Non-comedogenic & non-foaming hydrating formula',
                    '3 Essential Ceramides restore natural moisture barrier',
                    'MVE Technology provides 24-hour hydration',
                    'Fragrance-free and hypoallergenic',
                ],
                'usage_instructions' => 'Wet skin with lukewarm water. Massage cleanser into skin in a gentle, circular motion. Rinse.',
                'ingredients' => 'Aqua / Water / Eau, Glycerin, Cetearyl Alcohol, Peg-40 Stearate, Stearyl Alcohol, Potassium Phosphate, Ceramide NP, Ceramide AP, Ceramide EOP, Carbomer, Glyceryl Stearate, Behentrimonium Methosulfate.',
            ],
            [
                'user_id' => $seller1?->id,
                'category_id' => $catSkincare?->id,
                'category' => 'Skincare',
                'name' => 'COSRX Advanced Snail 96 Mucin Power Essence',
                'brand' => 'COSRX',
                'sku' => 'SKU-COS-SNAIL-100',
                'price' => 4850.00,
                'original_price' => 5500.00,
                'badge' => 'K-Beauty Favorite',
                'stock_quantity' => 95,
                'rating' => 4.9,
                'reviews_count' => 410,
                'is_featured' => true,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1608248597359-00f7e44a953e?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'Lightweight essence with 96.3% snail secretion filtrate to deeply nourish, repair, and glow.',
                'description' => 'Enriched with 96.3% skin-boosting snail secretion filtrate, this lightweight essence absorbs quickly into the skin to give you a natural, healthy glow. It soothes irritated skin, boosts elasticity, and delivers intense hydration.',
                'short_features' => [
                    '96.3% Snail Secretion Filtrate for skin barrier repair',
                    'Deeply hydrating without heavy greasy residue',
                    'Improves skin vitality and elasticity',
                    'Hypoallergenic & Dermatologist-tested',
                ],
                'usage_instructions' => 'After cleansing and toning, apply a small amount on your entire face. Gently pat using fingertips to aid absorption, and then continue with your moisturizers.',
                'ingredients' => 'Snail Secretion Filtrate, Betaine, Butylene Glycol, 1,2-Hexanediol, Sodium Polyacrylate, Phenoxyethanol, Sodium Hyaluronate, Allantoin, Ethyl Hexanediol, Carbomer, Panthenol, Arginine.',
            ],
            [
                'user_id' => $seller2?->id,
                'category_id' => $catSkincare?->id,
                'category' => 'Skincare',
                'name' => 'La Roche-Posay Anthelios UVMune 400 Invisible Fluid SPF50+',
                'brand' => 'La Roche-Posay',
                'sku' => 'SKU-LRP-SPF50-50',
                'price' => 6200.00,
                'original_price' => 6900.00,
                'badge' => 'Top Sunscreen',
                'stock_quantity' => 60,
                'rating' => 5.0,
                'reviews_count' => 189,
                'is_featured' => true,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'Ultra-high broad-spectrum UVA/UVB protection with invisible lightweight finish and no white cast.',
                'description' => 'The highest UVA protection in Anthelios history. Ultra-long UVA protection, ultra-resistant formula (water, sweat, and sand), ultra-invisible texture, non-greasy, non-sticky finish for all skin types including sensitive skin.',
                'short_features' => [
                    'MEXORYL 400 filter against ultra-long UVA rays',
                    'Zero white cast, ultra-fluid fast absorption',
                    'Sweat, water, and sand resistant',
                    'Non-comedogenic & ophthalmologically tested',
                ],
                'usage_instructions' => 'Shake well before use. Apply liberally 15 minutes before sun exposure and reapply every 2 hours or after towel drying.',
                'ingredients' => 'Aqua / Water, Alcohol Denat., Triethyl Citrate, Diisopropyl Sebacate, Silica, Ethylhexyl Salicylate, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Butyl Methoxydibenzoylmethane, Glycerin.',
            ],

            // --- MAKEUP ---
            [
                'user_id' => $seller1?->id,
                'category_id' => $catMakeup?->id,
                'category' => 'Makeup & Cosmetics',
                'name' => 'Fenty Beauty Gloss Bomb Universal Lip Luminizer - Fenty Glow',
                'brand' => 'Fenty Beauty',
                'sku' => 'SKU-FNT-GLOSS-FG',
                'price' => 7400.00,
                'original_price' => 8200.00,
                'badge' => 'Cult Favorite',
                'stock_quantity' => 45,
                'rating' => 4.9,
                'reviews_count' => 278,
                'is_featured' => true,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'The ultimate, gotta-have-it lip gloss with explosive shine that feels as good as it looks.',
                'description' => 'The definitive must-have lip gloss with incredible shine and an addictive peach-vanilla scent. Conditioned with nourishing Shea butter to leave lips looking instantly fuller and smoother without feeling sticky.',
                'short_features' => [
                    'Universal shimmering rose nude shade that flatters everyone',
                    'Super-sized XXL wand delivers smooth, even coverage in one swipe',
                    'Infused with conditioning Shea Butter',
                    '100% Cruelty-Free and Paraben-Free',
                ],
                'usage_instructions' => 'Wear Gloss Bomb alone or layer over lipstick as the finishing touch to the Fenty Face.',
                'ingredients' => 'Polybutene, Octyldodecanol, Bis-Diglyceryl Polyacyladipate-2, Tricaprylin, Cera Microcristallina/Microcrystalline Wax/Cire Microcristalline, Polyethylene, Silica Dimethyl Silylate, Butyrospermum Parkii (Shea) Butter.',
            ],
            [
                'user_id' => $seller1?->id,
                'category_id' => $catMakeup?->id,
                'category' => 'Makeup & Cosmetics',
                'name' => 'Huda Beauty Empowered Eyeshadow Palette',
                'brand' => 'Huda Beauty',
                'sku' => 'SKU-HUD-PAL-EMP',
                'price' => 19500.00,
                'original_price' => 22000.00,
                'badge' => 'Luxury Icon',
                'stock_quantity' => 25,
                'rating' => 4.9,
                'reviews_count' => 156,
                'is_featured' => true,
                'is_trending' => false,
                'image' => 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
                'short_description' => '18-pan multi-finish eyeshadow palette containing buttery mattes, molten metallics, and gel liner hybrids.',
                'description' => 'A fiercely pigmented game-changing palette with 18 power-packed shades. Includes innovative textures like hybrid gel liners, wet-look crushed flakes, high-shine metallics, and velvet-smooth mattes.',
                'short_features' => [
                    '18 ultra-pigmented gold, copper, brown, and bronze shades',
                    'Multi-finish: Buttery Mattes, Gel-Liners, High-Gloss Foils',
                    'Intense payoff with seamless blendability and zero fallout',
                    'Long-wearing 16-hour crease-free formula',
                ],
                'usage_instructions' => 'Build your base with matte shades. For high-impact metallic foil look, apply metallic shades using fingertips or dense synthetic brush.',
                'ingredients' => 'Mica, Talc, Zinc Stearate, Dimethicone, Octyldodecyl Stearoyl Stearate, Hydrogenated Polyisobutene, Boron Nitride, Silica, Calcium Sodium Borosilicate, Synthetic Fluorphlogopite.',
            ],
            [
                'user_id' => $seller2?->id,
                'category_id' => $catMakeup?->id,
                'category' => 'Makeup & Cosmetics',
                'name' => 'Maybelline SuperStay Matte Ink Liquid Lipstick - Pioneer',
                'brand' => 'Maybelline New York',
                'sku' => 'SKU-MAY-MAT-20',
                'price' => 2450.00,
                'original_price' => 2800.00,
                'badge' => '16H Transferproof',
                'stock_quantity' => 140,
                'rating' => 4.7,
                'reviews_count' => 520,
                'is_featured' => false,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1599733589046-10c005739ef9?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'Flawless matte liquid lipstick that lasts up to 16 hours without fading or transferring.',
                'description' => 'Ink your lips in up to 16-hour saturated liquid matte. SuperStay Matte Ink features a unique arrow applicator for precise application and is available in a range of super saturated shades.',
                'short_features' => [
                    '16-Hour long-lasting transfer-proof wear',
                    'Intense full-coverage opaque pigment in 1 swipe',
                    'Precision arrow tip applicator',
                    'Smudge-proof, kiss-proof, meal-proof',
                ],
                'usage_instructions' => 'Apply liquid lipstick in the center of your upper lip and follow the contours of your mouth. Glide the liquid lipstick across the entire bottom lip. Allow 2 minutes to dry.',
                'ingredients' => 'Dimethicone, Trimethylsiloxysilicate, Isododecane, Nylon-611/Dimethicone Copolymer, Dimethicone Crosspolymer, C30-45 Alkyldimethylsilyl Polypropylsilsesquioxane, Lauroyl Lysine.',
            ],

            // --- HAIRCARE ---
            [
                'user_id' => $seller1?->id,
                'category_id' => $catHaircare?->id,
                'category' => 'Haircare & Styling',
                'name' => 'Olaplex No. 3 Hair Perfector 100ml',
                'brand' => 'Olaplex',
                'sku' => 'SKU-OLA-N3-100',
                'price' => 8800.00,
                'original_price' => 9900.00,
                'badge' => 'Bond Builder',
                'stock_quantity' => 50,
                'rating' => 4.9,
                'reviews_count' => 310,
                'is_featured' => true,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'Global best-selling at-home treatment that reduces breakage and visibly strengthens hair.',
                'description' => 'An at-home bond-building treatment that reduces breakage and visibly strengthens hair, improving its look and feel. Patented OLAPLEX Bond Building Technology repairs broken disulfide bonds caused by heat, chemicals, and mechanical stress.',
                'short_features' => [
                    'Patented Bis-Aminopropyl Diglycol Dimaleate Bond Technology',
                    'Repairs damaged, bleached, and chemically treated hair',
                    'Restores healthy texture, shine, and manageability',
                    'Free of sulfates, phthalates, parabens, and gluten',
                ],
                'usage_instructions' => 'Apply to damp, towel-dried hair from roots to ends. Leave on for a minimum of 10 minutes (longer for severe damage). Rinse thoroughly, then shampoo and condition.',
                'ingredients' => 'Water (Aqua/Eau), Bis-Aminopropyl Diglycol Dimaleate, Propylene Glycol, Cetearyl Alcohol, Behentrimonium Methosulfate, Cetyl Alcohol, Phenoxyethanol, Glycerin, Hydroxyethyl Ethylcellulose, Stearamidopropyl Dimethylamine.',
            ],
            [
                'user_id' => $seller2?->id,
                'category_id' => $catHaircare?->id,
                'category' => 'Haircare & Styling',
                'name' => 'L\'Oréal Paris Elvive Extraordinary Oil Serum 100ml',
                'brand' => 'L\'Oréal Paris',
                'sku' => 'SKU-LOR-OIL-100',
                'price' => 2950.00,
                'original_price' => 3400.00,
                'badge' => 'High Shine',
                'stock_quantity' => 90,
                'rating' => 4.8,
                'reviews_count' => 195,
                'is_featured' => false,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'Enriched with 6 precious flower oils to deeply nourish dry hair, eliminate frizz, and provide mirror shine.',
                'description' => 'Elvive Extraordinary Oil is the iconic hair treatment for all hair types. Infused with 6 precious floral oils, it provides deep nourishment without weighing hair down, leaving locks silky soft and radiant.',
                'short_features' => [
                    '6 Rare Flower Extracts (Lotus, Chamomile, Tiare, Rose, Flax, Sunflower)',
                    'Multi-use: Heat protector, leave-in shine serum, pre-wash oil mask',
                    'Eliminates flyaways and tame frizzy hair instantly',
                    'Non-greasy lightweight absorption',
                ],
                'usage_instructions' => 'Rub 2-3 drops between the palms of your hands and apply along the lengths of wet or dry hair before heat styling or as a finishing touch.',
                'ingredients' => 'Cyclopentasiloxane, Dimethiconol, Chamomilla Recutita Extract / Matricaria Flower Extract, Cocos Nucifera Oil / Coconut Oil, Nelumbium Speciosum Extract / Nelumbo Nucifera Flower Extract, Benzyl Alcohol, Linalool, Parfum / Fragrance.',
            ],

            // --- FRAGRANCES ---
            [
                'user_id' => $seller1?->id,
                'category_id' => $catFragrance?->id,
                'category' => 'Fragrances & Perfumes',
                'name' => 'Maison Francis Kurkdjian Baccarat Rouge 540 EDP 70ml',
                'brand' => 'Maison Francis Kurkdjian',
                'sku' => 'SKU-MFK-BR540-70',
                'price' => 78000.00,
                'original_price' => 85000.00,
                'badge' => 'Ultra Luxury',
                'stock_quantity' => 10,
                'rating' => 5.0,
                'reviews_count' => 98,
                'is_featured' => true,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'The ultimate signature scent. Amber floral breeze of aerial jasmine notes, radiant saffron, and cedarwood.',
                'description' => 'Baccarat Rouge 540 eau de parfum lays on the skin like an amber floral and woody breeze. A poetic alchemy where the aerial notes of jasmine and the radiance of saffron carry mineral facets of ambergris and woody tones of freshly cut cedar.',
                'short_features' => [
                    'Top Notes: Grandiflorum Jasmine, Saffron',
                    'Heart Notes: Bitter Almond, Cedar Wood',
                    'Base Notes: Ambergris, Musky Woody Accord',
                    'Unrivaled projection and 24-hour beast-mode longevity',
                ],
                'usage_instructions' => 'Spray onto pulse points: wrists, inner elbows, neck, and behind ears.',
                'ingredients' => 'Alcohol, Parfum (Fragrance), Aqua (Water), Ethylhexyl Methoxycinnamate, Ethylhexyl Salicylate, Butyl Methoxydibenzoylmethane, Limonene, BHT, Linalool, Benzyl Benzoate.',
            ],
            [
                'user_id' => $seller2?->id,
                'category_id' => $catFragrance?->id,
                'category' => 'Fragrances & Perfumes',
                'name' => 'Kayali Vanilla 28 Eau De Parfum 50ml',
                'brand' => 'Kayali',
                'sku' => 'SKU-KAY-VAN-50',
                'price' => 28500.00,
                'original_price' => 31000.00,
                'badge' => 'Gourmand Favorite',
                'stock_quantity' => 30,
                'rating' => 4.8,
                'reviews_count' => 140,
                'is_featured' => true,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'Captivating masterpiece of nuanced sweetness with jasmine, Madagascan vanilla orchid, and Brazilian tonka.',
                'description' => 'Seduce the senses with Vanilla 28, a masterpiece of nuanced sweetness. Creamy jasmine and rich Madagascan vanilla orchid draw out the sweet softness of Brazilian tonka, musk, amber, and brown sugar.',
                'short_features' => [
                    'Notes: Vanilla Orchid, Tonka Bean Absolute, Brown Sugar, Amber Woods, Musk',
                    'Rich, warm gourmand profile created by Mona Kattan',
                    'Perfect for layering with floral and oud perfumes',
                ],
                'usage_instructions' => 'Spray on pulse points or layer over your favorite woody fragrance.',
                'ingredients' => 'Sd Alcohol 40-B/Alcohol Denat., Fragrance/Parfum, Water/Aqua/Eau, Butyl Methoxydibenzoylmethane, Ethylhexyl Methoxycinnamate, Ethylhexyl Salicylate, Coumarin, Citronellol, Geraniol.',
            ],

            // --- BODY CARE ---
            [
                'user_id' => $seller2?->id,
                'category_id' => $catBodycare?->id,
                'category' => 'Bath & Body Care',
                'name' => 'Sol de Janeiro Brazilian Bum Bum Cream 240ml',
                'brand' => 'Sol de Janeiro',
                'sku' => 'SKU-SDJ-BUM-240',
                'price' => 14500.00,
                'original_price' => 16500.00,
                'badge' => 'Viral Body Cream',
                'stock_quantity' => 40,
                'rating' => 4.9,
                'reviews_count' => 380,
                'is_featured' => true,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'Award-winning body cream that visibly tightens skin with caffeine-rich Guaraná and Cheirosa 62 scent.',
                'description' => 'Pronounced "boom boom" in Brazil, this fast-absorbing body cream helps visibly smooth and tighten the appearance of skin. Deliciously scented with irresistible pistachio and salted caramel notes.',
                'short_features' => [
                    'Guaraná Extract with 5x more caffeine than coffee for firming',
                    'Cupuaçu Butter, Açaí Oil, and Coconut Oil lock in moisture',
                    'Iconic Cheirosa 62 fragrance (Pistachio & Salted Caramel)',
                    'Fast absorbing with a subtle luminous sheen',
                ],
                'usage_instructions' => 'Massage in a circular motion to create warmth for better absorption and circulation. Use all over your body.',
                'ingredients' => 'Aqua (Water, Eau), Methyl Glucose Sesquistearate, Phenyl Trimethicone, Dodecane, Caprylic/Capric Triglyceride, Cetearyl Alcohol, Parfum (Fragrance), Glycerin, Cetyl Alcohol, Glyceryl Stearate Citrate.',
            ],

            // --- BEAUTY TOOLS ---
            [
                'user_id' => $admin?->id,
                'category_id' => $catTools?->id,
                'category' => 'Beauty Tools & Accessories',
                'name' => '12-Piece Professional Rose Gold Makeup Brush Set with Case',
                'brand' => 'Luxe Pro Tools',
                'sku' => 'SKU-BRUSH-SET-12',
                'price' => 4500.00,
                'original_price' => 6000.00,
                'badge' => '25% OFF',
                'stock_quantity' => 70,
                'rating' => 4.8,
                'reviews_count' => 125,
                'is_featured' => true,
                'is_trending' => false,
                'image' => 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'Handcrafted ultra-soft synthetic brushes for flawless foundation, powder, contour, and eye blending.',
                'description' => 'Professional 12-piece makeup brush collection crafted with premium vegan synthetic bristles, rose gold ferrules, and ergonomic wooden handles. Comes with a luxury vegan leather travel case.',
                'short_features' => [
                    '12 essential face and eye brushes for complete makeup look',
                    'Ultra-plush cruelty-free synthetic fibers that don\'t shed',
                    'Includes Foundation buffer, Powder dome, Angled contour, and 5 Eye blending brushes',
                    'Includes premium cylinder travel cylinder case',
                ],
                'usage_instructions' => 'Clean weekly with gentle brush shampoo and dry horizontally to preserve shape.',
                'ingredients' => 'Cruelty-free synthetic taklon bristles, rose gold aluminum ferrule, matte wooden handle.',
            ],

            // --- ORGANIC & HERBAL ---
            [
                'user_id' => $seller1?->id,
                'category_id' => $catOrganic?->id,
                'category' => 'Organic & Herbal',
                'name' => 'Pure Steam-Distilled Damascus Rose Water Face Mist 150ml',
                'brand' => 'Botanica Organics',
                'sku' => 'SKU-BOT-ROSE-150',
                'price' => 1250.00,
                'original_price' => 1500.00,
                'badge' => '100% Pure Organic',
                'stock_quantity' => 150,
                'rating' => 4.9,
                'reviews_count' => 245,
                'is_featured' => true,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1608248597359-00f7e44a953e?auto=format&fit=crop&w=800&q=80',
                'short_description' => '100% pure organic rose hydrosol that tones pores, hydrates skin, and revitalizes tired complexion.',
                'description' => 'Distilled from freshly harvested organic Damascus roses. Acts as a natural toner that balances pH levels, tightens enlarged pores, calms redness, and delivers instant botanical hydration throughout the day.',
                'short_features' => [
                    '100% Single-ingredient Pure Steam Distilled Rosa Damascena',
                    'Zero alcohol, artificial fragrances, or chemical preservatives',
                    'Soothes sensitive, irritated skin and reduces puffiness',
                    'Can be used as makeup setting spray and hair refresher',
                ],
                'usage_instructions' => 'Spritz liberally over face and neck after cleansing, or throughout the day whenever skin needs a refreshing burst of moisture.',
                'ingredients' => '100% Pure Organic Rosa Damascena Flower Water.',
            ],
            [
                'user_id' => $seller2?->id,
                'category_id' => $catOrganic?->id,
                'category' => 'Organic & Herbal',
                'name' => 'Cold-Pressed Jamaican Black Castor Oil 120ml',
                'brand' => 'Botanica Organics',
                'sku' => 'SKU-BOT-CAST-120',
                'price' => 1850.00,
                'original_price' => 2200.00,
                'badge' => 'Hair Growth Booster',
                'stock_quantity' => 110,
                'rating' => 4.8,
                'reviews_count' => 160,
                'is_featured' => false,
                'is_trending' => true,
                'image' => 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=800&q=80',
                'short_description' => 'Traditional roasted castor oil that stimulates hair follicles, thickens eyebrows, and boosts eyelash growth.',
                'description' => 'Unrefined and 100% pure Jamaican Black Castor Oil rich in ricinoleic acid and essential fatty acids. Deeply penetrates roots to promote thicker, denser hair growth and condition brittle ends.',
                'short_features' => [
                    'Traditional artisanal roasting process for maximum nutrient density',
                    'Promotes eyebrow, eyelash, and scalp hair regrowth',
                    'Seals moisture into dry split ends',
                    '100% Pure, Hexane-Free, Unrefined',
                ],
                'usage_instructions' => 'Massage a few drops directly into scalp or eyebrows before bedtime. Leave on overnight and wash in the morning.',
                'ingredients' => '100% Pure Ricinus Communis (Castor) Seed Oil.',
            ],
        ];

        foreach ($products as $pData) {
            $product = Product::updateOrCreate(
                ['slug' => Str::slug($pData['name'])],
                [
                    'user_id' => $pData['user_id'] ?? $admin?->id,
                    'category_id' => $pData['category_id'],
                    'name' => $pData['name'],
                    'brand' => $pData['brand'],
                    'sku' => $pData['sku'],
                    'category' => $pData['category'],
                    'price' => $pData['price'],
                    'original_price' => $pData['original_price'],
                    'cost_price' => $pData['price'] * 0.65,
                    'badge' => $pData['badge'],
                    'stock_quantity' => $pData['stock_quantity'],
                    'in_stock' => true,
                    'rating' => $pData['rating'],
                    'reviews_count' => $pData['reviews_count'],
                    'is_featured' => $pData['is_featured'],
                    'is_trending' => $pData['is_trending'],
                    'image' => $pData['image'],
                    'short_description' => $pData['short_description'],
                    'description' => $pData['description'],
                    'short_features' => $pData['short_features'],
                    'usage_instructions' => $pData['usage_instructions'],
                    'ingredients' => $pData['ingredients'],
                    'is_active' => true,
                    'approval_status' => 'approved',
                ]
            );

            // Add gallery image
            ProductImage::firstOrCreate(
                [
                    'product_id' => $product->id,
                    'image_path' => $pData['image'],
                ],
                [
                    'is_primary' => true,
                    'sort_order' => 1,
                ]
            );
        }
    }
}
